services:
  awslambda:
    command: tail -f /dev/null
    build: ./
    volumes:
      - ./:/home/lalupe  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    volumes:
      - ./category/assets/:/usr/share/nginx/html/category
      - ./product/assets/:/usr/share/nginx/html/product
      - ./user/assets/:/usr/share/nginx/html/user
    environment:
      URLS: "[{ url: \"./category/swagger.json\", name: \"Category\" },{ url: \"./product/swagger.json\", name: \"Product\" },{ url: \"./user/swagger.json\", name: \"User\" }]"