services:
  awslambda:
    command: tail -f /dev/null
    build: ./
    volumes:
      - ./:/home/shopy  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    volumes:
      - ./category/assets/swagger.json:/usr/share/nginx/html/category.json
      - ./product/assets/swagger.json:/usr/share/nginx/html/product.json
      - ./user/assets/swagger.json:/usr/share/nginx/html/user.json
    environment:
      URLS: "[{ url: \"./category.json\", name: \"Category\" },{ url: \"./product.json\", name: \"Product\" },{ url: \"./user.json\", name: \"User\" }]"